name: msbo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - pip=23.3
  - numpy=1.26.2
  - scipy=1.11.4
  - matplotlib=3.8.2
  - pandas=2.1.3
  - seaborn=0.13.2
  - pyyaml=6.0.1
  - scikit-learn=1.3.2
  - pip:
      - torch==2.1.1
      - gpytorch==1.8.1
      - botorch==0.6.6
      - openpyxl==3.1.5
